import Head from 'next/head';
import Main from './Main';
import Header from './Header';
import Footer from './Footer';

import styles from '../styles/Layout.module.scss';

export default function Layout() {
  return (
    <div className={styles.layout}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.0/css/all.css"
        />
      </Head>
      <Header />
      <Main />
      <Footer />
    </div>
  );
}
